// Put all hard coded data into config file
// Called as constants file in some companies
// this file could be different for production or staging or testing

export const IMG_CDN_URL =
    "https://b.zmtcdn.com/web_assets/81f3ff974d82520780078ba1cfbd453a1583259680.png";

export const restaurantList = [
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "117123",
            name: "Milk Bar",
            uuid: "fd074868-4223-4d81-9b36-e827e168d3f9",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "s2fvlgmbjpx2fuyjtwj1",
            cuisines: ["Italian", "Chinese"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 45,
            minDeliveryTime: 45,
            maxDeliveryTime: 45,
            slaString: "45 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
                restaurant: "milk-bar-civil-line-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "19,civil lines roorkee near IIT gate",
            locality: "IIT gate",
            parentId: 136175,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "60% off",
                shortDescriptionList: [
                    {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=5689098~p=1~eid=00000185-d81e-44e9-1012-6a3900090158",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "117123",
                deliveryTime: 45,
                minDeliveryTime: 45,
                maxDeliveryTime: 45,
                lastMileTravel: 0.800000011920929,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "204036",
            name: "Punjabi Dhaba- P.D.",
            uuid: "169a34c9-6daa-49c2-a32b-2e5dba27bdf8",
            city: "152",
            area: "Bus Stand",
            totalRatingsString: "10000+ ratings",
            cloudinaryImageId: "cszzqdlhjchojjrq6rmx",
            cuisines: ["Punjabi", "North Indian"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            slaString: "28 MINS",
            lastMileTravel: 0.4000000059604645,
            slugs: {
                restaurant: "punjabi-dhaba--p.d.-civil-lines-civil-lines",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "Punjabi Dhaba, Dehradun Rd, Dharun, Roorkee, Uttarakhand, India",
            locality: "Civil Lines",
            parentId: 162241,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.4 kms",
            hasSurge: false,
            sla: {
                restaurantId: "204036",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 0.4000000059604645,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 10000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "365418",
            name: "Baap Of Rolls",
            uuid: "a5818d35-fb9d-4deb-ab07-89712b2c385e",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "qzsyuqvwgfj4n5daujir",
            cuisines: ["Arabian"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 27,
            minDeliveryTime: 27,
            maxDeliveryTime: 27,
            slaString: "27 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant: "baap-of-rolls-iit_roorkee-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "22 CIVIL LINES,OPP. MILK BAR, ROORKEE ,Roorkee,Hardwar,Uttarakhand-247667",
            locality: "IIT_Roorkee",
            parentId: 14310,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "60% off",
                shortDescriptionList: [
                    {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "365418",
                deliveryTime: 27,
                minDeliveryTime: 27,
                maxDeliveryTime: 27,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.2",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "615616",
            name: "Burger Singh (Big Punjabi Burgers)",
            uuid: "5022c2d8-102a-41d7-a424-b7242d884c2c",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "dzkvdkgzh9rnecirrrml",
            cuisines: [
                "Burgers",
                "Snacks",
                "Desserts",
                "Beverages",
                "Fast Food",
                "American",
                "Indian",
                "Biryani",
            ],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 1.2999999523162842,
            slugs: {
                restaurant:
                    "burger-singh-(big-punjabi-burgers)-iit_roorkee-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "SHOP NO. 11, UGF, CITY PRIDE COMPLEX , PREM MANDIR ROAD , Roorkee, Hardwar, Uttarakhand 247667",
            locality: "IIT_Roorkee",
            parentId: 375065,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "60% off",
                shortDescriptionList: [
                    {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=5706015~p=4~eid=00000185-d81e-44e9-1012-6a3a0009046f",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.2 kms",
            hasSurge: false,
            sla: {
                restaurantId: "615616",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 1.2999999523162842,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.1",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "500232",
            name: "Aayan Hyderabadi Chicken Biryani",
            uuid: "3f12fb3d-939b-4156-b44d-71838dea33a1",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "eqdgredzgrhblkyevr0i",
            cuisines: ["Biryani"],
            tags: [],
            costForTwo: 20000,
            costForTwoString: "₹200 FOR TWO",
            deliveryTime: 30,
            minDeliveryTime: 30,
            maxDeliveryTime: 30,
            slaString: "30 MINS",
            lastMileTravel: 1.899999976158142,
            slugs: {
                restaurant:
                    "aayan-hyderabadi-chicken-biryani-iit_roorkee-iit_roorkee-2",
                city: "roorkee",
            },
            cityState: "152",
            address: "Railway Station Roorkee",
            locality: "IIT_Roorkee",
            parentId: 26354,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Biryani on above 449rs",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Biryani on above 449rs",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Biryani on above 449rs",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "500232",
                deliveryTime: 30,
                minDeliveryTime: 30,
                maxDeliveryTime: 30,
                lastMileTravel: 1.899999976158142,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "395878",
            name: "Hotel Prakash & Restaurant",
            uuid: "9b247722-502d-465b-b6a8-302a2ff4192f",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "hnuhnz1xgxvlzadfhpvs",
            cuisines: [
                "Chinese",
                "North Indian",
                "South Indian",
                "Pizzas",
                "Snacks",
                "Chaat",
                "Biryani",
                "Salads",
                "Desserts",
            ],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 28,
            minDeliveryTime: 28,
            maxDeliveryTime: 28,
            slaString: "28 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant:
                    "hotel-prakash-&-restaurant-iit_roorkee-iit_roorkee-2",
                city: "roorkee",
            },
            cityState: "152",
            address: "19 Civil Lines, Roorkee",
            locality: "IIT_Roorkee",
            parentId: 247268,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "50% off",
                shortDescriptionList: [
                    {
                        meta: "50% off | Use MISSEDYOU",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code MISSEDYOU",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "50% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use MISSEDYOU",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code MISSEDYOU",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "395878",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "422614",
            name: "Roms Pizza",
            uuid: "d7c20a65-8d49-48e5-ada5-285921c6c692",
            city: "152",
            area: "IIT Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "ipcryddnz3cixb4185l6",
            cuisines: ["Pizzas"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 44,
            minDeliveryTime: 44,
            maxDeliveryTime: 44,
            slaString: "44 MINS",
            lastMileTravel: 2.0999999046325684,
            slugs: {
                restaurant: "roms-pizza-civil-lines-civil-lines",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "STAR FOOD,MOHANPURA DOUBLE  PHATAK,DELHI ROAD,ROORKEE, Roorkee,  Hardwar, Uttarakhand-247667",
            locality: "Civil Lines",
            parentId: 12143,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "60% off",
                shortDescriptionList: [
                    {
                        meta: "60% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "60% off up to ₹120 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=5714083~p=7~eid=00000185-d81e-44e9-1012-6a3b0009075d",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2 kms",
            hasSurge: false,
            sla: {
                restaurantId: "422614",
                deliveryTime: 44,
                minDeliveryTime: 44,
                maxDeliveryTime: 44,
                lastMileTravel: 2.0999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "541013",
            name: "Oregano",
            uuid: "7a8b6cd2-0407-41d8-9e25-7f6a0922fff9",
            city: "152",
            area: "Civil Lines",
            totalRatingsString: "100+ ratings",
            cloudinaryImageId: "vq6eisia40xoixy7wkra",
            cuisines: ["Chinese", "American", "Pizzas"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 37,
            minDeliveryTime: 37,
            maxDeliveryTime: 37,
            slaString: "37 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant:
                    "oregano-a-global-kitchen-(a-unit-of-kapoor-and-son-iit_roorkee-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "28, CIVIL LINES, ROORKEE HARDWAR",
            locality: "IIT_Roorkee",
            parentId: 14662,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "541013",
                deliveryTime: 37,
                minDeliveryTime: 37,
                maxDeliveryTime: 37,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.6",
            totalRatings: 100,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "115753",
            name: "Pizza Hut",
            uuid: "417fe773-c4b1-439c-b3eb-4430e9e56b93",
            city: "152",
            area: "Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "jtm2las3gu6vr3vrrn27",
            cuisines: ["Pizzas"],
            tags: [],
            costForTwo: 35000,
            costForTwoString: "₹350 FOR TWO",
            deliveryTime: 35,
            minDeliveryTime: 35,
            maxDeliveryTime: 35,
            slaString: "35 MINS",
            lastMileTravel: 1.600000023841858,
            slugs: {
                restaurant: "pizza-hut-civil-lanes-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "2, Civil Lines Roorkee, Uttrakhand",
            locality: "Civil Lanes",
            parentId: 721,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "50% off",
                shortDescriptionList: [
                    {
                        meta: "50% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "50% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "1.6 kms",
            hasSurge: false,
            sla: {
                restaurantId: "115753",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                lastMileTravel: 1.600000023841858,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.9",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "395875",
            name: "Prakash Sweets",
            uuid: "77e65bea-4252-49ea-bf6b-132f40df9419",
            city: "152",
            area: "Civil Lines",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "qgturk074a3o9kwicocb",
            cuisines: ["Desserts", "Snacks", "Sweets"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 29,
            minDeliveryTime: 29,
            maxDeliveryTime: 29,
            slaString: "29 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant: "prakash-sweets-iit_roorkee-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "19 civil lines, Roorkee",
            locality: "IIT_Roorkee",
            parentId: 160530,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "50% off",
                shortDescriptionList: [
                    {
                        meta: "50% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "50% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "50% off up to ₹100 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=5689128~p=10~eid=00000185-d81e-44e9-1012-6a3c00090a12",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "395875",
                deliveryTime: 29,
                minDeliveryTime: 29,
                maxDeliveryTime: 29,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.4",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "117227",
            name: "Pizza Paradise",
            uuid: "c9138a77-3094-4382-84b9-f5383f46e3ae",
            city: "152",
            area: "Azad Nagar Chowk",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "jqdu3cldrrg22ls9wwaw",
            cuisines: ["Italian"],
            tags: [],
            costForTwo: 25000,
            costForTwoString: "₹250 FOR TWO",
            deliveryTime: 39,
            minDeliveryTime: 39,
            maxDeliveryTime: 39,
            slaString: "39 MINS",
            lastMileTravel: 2.4000000953674316,
            slugs: {
                restaurant: "pizza-paradise-azad-nagar-chowk-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "azad nagar chowk,Dehradun road near Prakash sweets",
            locality: "IIT_Roorkee",
            parentId: 8997,
            unserviceable: false,
            veg: true,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Capsicum Pizza",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Capsicum Pizza on orders above Rs 449",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Capsicum Pizza on orders above Rs 449",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "2.4 kms",
            hasSurge: false,
            sla: {
                restaurantId: "117227",
                deliveryTime: 39,
                minDeliveryTime: 39,
                maxDeliveryTime: 39,
                lastMileTravel: 2.4000000953674316,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "3.8",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "116583",
            name: "Food point",
            uuid: "5afa36bc-856c-453e-93ec-c112d39ba3dd",
            city: "152",
            area: "Civil Lines",
            totalRatingsString: "5000+ ratings",
            cloudinaryImageId: "vhycbkzlyapoz8joiyyq",
            cuisines: ["Indian", "Tandoor"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 33,
            minDeliveryTime: 33,
            maxDeliveryTime: 33,
            slaString: "33 MINS",
            lastMileTravel: 0.8999999761581421,
            slugs: {
                restaurant: "food-point-civil-lines-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "Food Point, Near Hotel Center Point, Civil Lines, Roorkee",
            locality: "IIT_Roorkee",
            parentId: 3967,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "116583",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 0.8999999761581421,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 5000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "403832",
            name: "KFC",
            uuid: "5ccd528e-a540-4e05-8674-f675151b706c",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "500+ ratings",
            cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
            cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
            tags: [],
            costForTwo: 40000,
            costForTwoString: "₹400 FOR TWO",
            deliveryTime: 38,
            minDeliveryTime: 38,
            maxDeliveryTime: 38,
            slaString: "38 MINS",
            lastMileTravel: 3,
            slugs: {
                restaurant: "kfc-nehru-nagar-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "KFC Restaurant, Shop No 176 Ground Floor , Nehru Nagar , Roorkee Uttarakhand 247667",
            locality: "Nehru Nagar",
            parentId: 547,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "20% off",
                shortDescriptionList: [
                    {
                        meta: "20% off | Use SWIGGYIT",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "20% off up to ₹50 | Use code SWIGGYIT",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "20% OFF",
                shortDescriptionList: [
                    {
                        meta: "Use SWIGGYIT",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "20% off up to ₹50 | Use code SWIGGYIT",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            ribbon: [
                {
                    type: "PROMOTED",
                },
            ],
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID:
                "cid=5775183~p=13~eid=00000185-d81e-44e9-1012-6a3d00090d20",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "3 kms",
            hasSurge: false,
            sla: {
                restaurantId: "403832",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: true,
            avgRating: "4.0",
            totalRatings: 500,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "117150",
            name: "Tanisha's Royal Hyderabadi Biryani",
            uuid: "436d0a95-84ba-408e-a5a3-0b40ee9ac8ab",
            city: "152",
            area: "IIT_Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "gmg9kyenjqypnmmmdqxk",
            cuisines: ["Indian"],
            tags: [],
            costForTwo: 30000,
            costForTwoString: "₹300 FOR TWO",
            deliveryTime: 31,
            minDeliveryTime: 31,
            maxDeliveryTime: 31,
            slaString: "31 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
                restaurant:
                    "tanishas-royal-hyderabadi-biryani-civil-lines-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address: "19 Prince complex civil line",
            locality: "IIT_Roorkee",
            parentId: 201004,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "117150",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 0.800000011920929,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.0",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
    {
        type: "restaurant",
        data: {
            type: "F",
            id: "210285",
            name: "Snacks Point",
            uuid: "862d3070-638b-4eaa-8a05-1674b607ccbb",
            city: "152",
            area: "Indian Institute Of Technology Roorkee",
            totalRatingsString: "1000+ ratings",
            cloudinaryImageId: "nvmkh3nckqid1doufsn1",
            cuisines: ["North Indian", "Chinese"],
            tags: [],
            costForTwo: 15000,
            costForTwoString: "₹150 FOR TWO",
            deliveryTime: 24,
            minDeliveryTime: 24,
            maxDeliveryTime: 24,
            slaString: "24 MINS",
            lastMileTravel: 0.800000011920929,
            slugs: {
                restaurant: "snacks-point-iit_roorkee-iit_roorkee",
                city: "roorkee",
            },
            cityState: "152",
            address:
                "Prakash Sweets, Haridwar Rd, Indian Institute of Technology Roorkee, Roorkee, Uttarakhand, India",
            locality: "IIT_Roorkee",
            parentId: 190298,
            unserviceable: false,
            veg: false,
            select: false,
            favorite: false,
            tradeCampaignHeaders: [],
            aggregatedDiscountInfo: {
                header: "Free delivery",
                shortDescriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Boondi Raita",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Boondi Raita on orders above Rs 349",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            aggregatedDiscountInfoV2: {
                header: "60% OFF",
                shortDescriptionList: [
                    {
                        meta: "Free Delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                ],
                descriptionList: [
                    {
                        meta: "Free delivery",
                        discountType: "FREE_DELIVERY",
                        operationType: "RESTAURANT",
                    },
                    {
                        meta: "Free Boondi Raita on orders above Rs 349",
                        discountType: "Freebie",
                        operationType: "RESTAURANT",
                    },
                ],
                subHeader: "",
                headerType: 0,
                superFreedel: "",
            },
            chain: [],
            feeDetails: {
                fees: [],
                totalFees: 0,
                message: "",
                title: "",
                amount: "",
                icon: "",
            },
            availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
            },
            longDistanceEnabled: 0,
            rainMode: "NONE",
            thirdPartyAddress: false,
            thirdPartyVendor: "",
            adTrackingID: "",
            badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
            },
            lastMileTravelString: "0.8 kms",
            hasSurge: false,
            sla: {
                restaurantId: "210285",
                deliveryTime: 24,
                minDeliveryTime: 24,
                maxDeliveryTime: 24,
                lastMileTravel: 0.800000011920929,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
            },
            promoted: false,
            avgRating: "4.1",
            totalRatings: 1000,
            new: false,
        },
        subtype: "basic",
    },
];
